language: node_js
node_js: 8.9.1
before_install: sh -e /etc/init.d/xvfb start
script:
- if [ "x${CORE_BRANCH}x" != "xx" ]; then npx publish_yalc_package .downstream_cache/core https://github.com/ui-router/core.git && yalc add @uirouter/core && export UPSTREAM_PKGS=@uirouter/core; fi
- tsc
- yarn test
- npx generate_docs
- yarn test:downstream
env:
  matrix:
  - CORE_BRANCH=
  - CORE_BRANCH=master
notifications:
  slack:
    on_success: never
    rooms:
      secure: alXA+pERLtF4DNctl+WaISO3uzUA/JzVCzSrDlNsV9Jvx1HdAqRNbrrnNYzCZBIU6OOv5YBGFbq79v5NPKzMPzoR8dp3PahlxRgucxALweoTCXY5DuDHVSI9ULLl2PND7QOfKyUALuAz5nmT7omPVxRKCpBkVsqewLfMeW1MRgE=
sudo: false
cache:
  yarn: true
  directories:
  - ".downstream_cache"
  - node_modules
