language: node_js
node_js: 8.9.1
before_install:
- sh -e /etc/init.d/xvfb start
- export PATH=$HOME/.yarn/bin:$PATH
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
script:
- if [ "x${CORE_BRANCH}x" != "xx" ]; then npx publish_yalc_package .downstream_cache/core https://github.com/ui-router/core.git && yalc add @uirouter/core ; fi
- tsc &&
  yarn test &&
  yarn docs &&
  yarn test:downstream
env:
  matrix:
  - CORE_BRANCH=
  - CORE_BRANCH=master UPSTREAM_PKGS=@uirouter/core
notifications:
  slack:
    on_success: never
    rooms:
      secure: alXA+pERLtF4DNctl+WaISO3uzUA/JzVCzSrDlNsV9Jvx1HdAqRNbrrnNYzCZBIU6OOv5YBGFbq79v5NPKzMPzoR8dp3PahlxRgucxALweoTCXY5DuDHVSI9ULLl2PND7QOfKyUALuAz5nmT7omPVxRKCpBkVsqewLfMeW1MRgE=
sudo: false
git:
  depth: 3
cache:
  directories:
  - node_modules
  - ".downstream_cache"
