language: node_js
node_js:
- 8.9.1
cache:
  directories:
  - "$HOME/.npm"
  - node_modules
before_script:
- greenkeeper-lockfile-update
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile@1
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: dWlJrBiWE39jBDz7MGp6O8NHAaAGE1miI55VyhZEi4l6pgqqe+8qTcyrJLbakvWCmhg5r8X32raKQONT3x3qgrlxfv6ALBe/Ai4zmit+5LMuZcM7Xdbw/KSoqq6p6dSzURhwzIaLY5FBwfZY835b8HlFUfcQc01s3Sa9CCN8ci5C6tabEfnZJma+ZeEDuL9WrSEYmcrObbt0WezEQ6w9/RP5OPWNnNYfM5FEd5UC17Zw3C/OCdq8KJ1azPMBrHlcdNZiTUlgmTVaZOMADscBaExvaa4weofnmYTknw0yIMktciu6/kp+BhRt1UDyiH2T9r108O7psji/gW1noghomtq38j2yRH/JYK3W7DkvW9ZE+/aK4r7oZUX2PT7qDJL+uZO0m7ZO0CVIcPreh0xojcg2EOhmXrUIb6tvplhxW2ZZefc9A81sHz05CuAqLsQGgFc3sdc22YnBshy1ZsLbe8wXQXw9gVvICFosNMcgSpVAEHXzYFUrreyiNNCZ8ReVrlXRPzlmNGQBf+cth6xPFTkV+JCDqssg9OL9qCxgiRGPbbQ9wQXucoB63Vs2So+BFFncpor7xoTzxiqHgLqHY/qFfaiAoai00u75ziIvvTCGECPEyHjMP+jkoXzdsOcvLsj4n0jEDWUWWelCPBS+oJRUri7S7UcpeVGywEjT7Vs=
