language: node_js
node_js:
  - "4.3"

cache:
  yarn: true
  bundler: true
  directories:
    - $HOME/.yarn-cache
    - $HOME/.cache/yarn
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./nodeserver.sh > /dev/null &

script:
  - tsc
  - yarn test

sudo: false

git:
  depth: 3

notifications:
  slack: angularbuddies:b6leQM9gkBCW0S7MNDsELpqU

