language: node_js
node_js:
- '7.9'

cache:
  yarn: true
  bundler: true
  directories:
  - "$HOME/.yarn-cache"
  - "$HOME/.cache/yarn"
  - node_modules

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile@1


install:
- yarn

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- "./nodeserver.sh > /dev/null &"
- greenkeeper-lockfile-update

script:
- tsc
- yarn test

after_script: greenkeeper-lockfile-upload

sudo: false

git:
  depth: 3

notifications:
  slack:
    secure: VlSFXHFYU4jlc5OSX0JZcZfXY73uIELlQJ7sYadyW7Cu3SqeTGSTxhGxDBir5aLVgONXFXXW2JJTKIXK3Sdl7+IpCetR5cgqoYNaINMgOU9uw4XVwZ4BEQoQlYeP6YaR5GJNaF1tz5H/8aon/RlNqiaRzaUUHsmmI7tTvGuceT0d77IxwmWZbSQKK3cxRK0LtlOzD0yAlVE+3omei94DXlDMcUi3wy83UjOhc+SJHp9w5Z0CsAjRe8pD1nMDfaYG2F7TssAqdnbfb9EE9m3GqIoJXensQtoBkAQjUdAb5Zr4Zfdo+sR73vzN8EM1TVL7C84CU8SmEOG88AVjbJldOzfW3jor2hM839AjXQ0yQlUONP1TfI5YqfnrfA2N6Xw2yABXp1A/dePzz78RgfhchesKfUeS8Rm8kDp/J2Dqq0UMyt7P3COckJK04TfRjzZeX1egWVDlLgDWt2/sxjk97vppkPrjAg6m/wQK/ImZaAqMgkNaXXp+D3EB8AWuoq3aOp4iITMZ4Xy1IC+sXF4RWqPxnz3W0TaY8fYJvAC3PAfydLGy2bKJ/ZXsAQHwHt9wDUOiKbAHHfo8lUMv2SVvqXbQQMFUuk6WtZg/YV6IQNnwkQW7q9FgvopnI8sSFek9R4h+2+IB6R+jQ7+nBRAcXGftOsiNXVymmLQfAX8FYYc=

env:
  global:
    secure: bEGHePu9rkjcy5Pq3RQQfCIRzAfCSxH7dZsdOJd3pAXEGbkhuCOAGFV0v+NVbRBWNYv0yIExwwu2VOVfAPGqmmuhzE8Uq/WZeLWUbUA1oSIN7t9IkYRKIdoE36o85eyRxSTP6w3dtMHXLeMvPbgtgEUVrgPztBVe3ySoQ+nA3jbgZ/fBpuEevJ2dAxwybbtRwZBflplUumpwmy1pSiLHptdFXsxmmLr0hOjx+WZd38jMZo4H4vV9zo6wz34hjf+j1f0jsjmsKgpRVPLADtLTcqIfEegSG7vLmlFJLGBtBZ6UhIioZseZTVOi2wq1hK0E+3SzPJVXhu3h7VsIBVgCaaYJQ07p7q9LszwWwxHHzePLBtV77J6mJ1zZFbS/PHmVHnfU/gz5+l2Te2KSkvFYbq9uVXd4CLLeR1xdECwX8qiXMtUOk7IauVVzFtLCPRVksmEjClJNf1tAi+j9nKezYHQ8LPSqTyoxo/0PhQJ0U3pCQuKGTxO9lDi63Gks9lr87N+yrn81W+2wbGKL6iqItKPAQ5Tcl5FbhmwUk40p0Sz1KNjBWepREQAeCgRKFN4y/Xhi6Mn1TydwE9zHXdfIiWNYaxl0LjXMnAMahvO2+m5NClDWhzBii21JsdMyUS3TUFGyVIfok2M+uaM2NZn7GLNRSOGarBpLhF/5lci/9kY=
