language: node_js
node_js:
- '7.9'
script:
- npm run build
sudo: false
git:
  depth: 2
notifications:
  slack:
    secure: Xq9gHjFydM6v38ncMw8kVEV07mRctwSrr4opdd8ESHYtlCJq2xoYeS0z6teZKcfC/OF26VU5VhOwVsMBfCVJYX2HuHz8u01rJU7/j21UvKFjrzAx620oCzbUFB+iN8oPm7w/S4d24OPHkZbQGWonQm0W3GTZRtbcmJ/iblzq7W5uG4TdYp2ILjxiS8PTDzACeq1qM1MpgKoRmjAXEDzoi4QQw4MAVzrQTQMvnpx9jQxTsMNOR9uVvb9yUkR7hGGPYYYT5DQOlIxzaTYKggXjPr+Z3OA/0RK/rphH4Kst5+CmNwY0DRGe2MahsVmHvZg4GEdQfLMLEhNHAo1anfM2JicDFWV/0vOAsGx+CPf7G8MgBk3nHfZ7+SzXPyU7VhWDisZ/NCmb5ZZ+c9gqd0KU4OJlhlxeB03eCLcGBKTUzfxpCeH/QSMUij0HcbVLtjDww9alNppXBQkFW3GTYoGf1tmXayEiXSsvtD2W/6zsOB7t3NzDARI8O/Ozkg7QB9cC/SpijHMHfh0AzVTO9OzMw5+GNkF1dOjB1VCeYiIU6xzPxN0WO9UXLq1dBY4KjZ5XoDuQpMzY537sj5GyIjlVBark+U4RizMnWRshiNjwG92PHP50wcLmbmFs1ohPhM3e2v1z+JtFmhh1kkcyW+XYwjjX+LkG0zM7Ch+VOCFAp+A=
