language: node_js
node_js: lts/*
services:
  - xvfb
before_install:
  - sudo apt-get install libgconf-2-4
  - export PATH=$HOME/.yarn/bin:$PATH
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
script:
  - yarn build &&
    yarn test &&
    yarn test:downstream
notifications:
  slack:
    on_success: never
    rooms:
      secure: KO9V+uK5JxXBXDu7E908VK+7Cfkr5oi2b0IrdEPbzVjqhAfcmG8IB5U2JvmAL8Az1UA+O5LpIa+soacD9XDqTfVisc+LUp+oZv1eFHy+sRx4VUyyEWPs0siEZBdfahYaMok6lNb6bWKx06lZ2L7/bN34ROHNv4t42kXWX8H5OdbkW3ipIwO9ZL7yNcQfcJ8N68XutJWS/s9RwRNFP9g9fwwsV5aBiGUDHu8wAVpCMvfVJhpgfci5p5fFMEGYsVb0W/PAD6Xt4FWYbwE9AB5dXR9Q6tRH9Y4SnJbZ1AY4cc0hss21SnOvwoTLIUwabY7iQAHodqsQLDNvz49hkSLd9Y55umFp/5gXSbJBue92Q2hwULwaayjizn0SYT2Mn2e0gEEsJVWq9/S129LA+MmIE11EQ2obx1EmX4aznvlfMGzyidwmniYY3wRKptulB6y66OSuD4Wq15vTdv5gCmRxQihV9mcTbYVMA+03WEaFnw3/W+Rd4h9Pj5l3ctpjEs3WeYJFIW2tU606iJYvQRuEFloWyZo6CX5vZpxD81O9ao74qgYk2PMRNJ9zH1CmIWE2EhVZhN1oISSsu9Caj0XsAJ78owrEvqLEsWP9gnslIK3KpUsOhe/PM958fngqHnjA0ovM04FRjsL0L3azyvz+IaKof8UyE28j2dMg6gl8YR0=
sudo: false
git:
  depth: 3
cache:
  directories:
    - node_modules
    - '.downstream_cache'
