language: node_js
node_js: 8.9.1
before_install:
- sh -e /etc/init.d/xvfb start
- yarn global add greenkeeper-lockfile@1 yalc
before_script: greenkeeper-lockfile-update && greenkeeper-lockfile-upload
script:
- if [ "x${CORE_BRANCH}x" != "xx" ] ; then ./node_modules/.bin/publish_yalc_package
  .downstream_cache/core https://github.com/ui-router/core.git && yalc add @uirouter/core
  ; fi
- yarn test && yarn test:downstream
env:
  global:
    secure: J0z1REjKvZDeSQtvQULqLkCU88LH1PKlXJM9vHIr/xIAKqQRsZsfefBqcQwGw5HeYvKJ0VToiEjRKzbTDiTx+OvsY1vroWVjmJx3SqeXfW+lmcPP0tcg4SIHy2een711GFpEXLicbAG3LkmGMJxJj/y2S2Tl+iwV7GNvlVZagrqXwSOFsSd0pgN4KjYk20yNnJi+yq7jeCYG/Ta9LcCJ4LUkiMU/5QxObzfd0cOP/KIJqaV1TobO4vjOJA5RY+TllnTfrguEHG18xX3Y0aD7t0x5zynZeccfIWybXwsWv/TWvu/0XBIk7eM7aGENNZxxYxfIjsadQa3d+qlnkrcvA9TH20or8NXWCJYGCZIX2kOB7StmuHWI7eqTKNfLHJWEM6hkTU+gfQMe9qbwVbPaEgfaG3YjIvZ4y8yeUGY/MpSKYYr8HC7t9UyfnFPleke7Kk4JkBgZ6gSGpgDKb9TcnpuMIWy/6jN5+ZXqgeX4xeN0yd2u4xussLFGcNks82d366Z41fRIWH+wpfZCPsbB2QKE7pn1bWuQ2rZO1X0CzwtpQoQ3kAS+6EE6eRapqBSgTLstWXf3yf50xs8PlBCmR0s4Ft+YquyBcxfzekVP3oG1rfMoarq2+mKCcb7ckLGcC6IDx/QeIaHWh+rjZTwAoYqsYtMW13gT0KtVmeKHlFw=
notifications:
  slack:
    on_success: never
    rooms:
      secure: KO9V+uK5JxXBXDu7E908VK+7Cfkr5oi2b0IrdEPbzVjqhAfcmG8IB5U2JvmAL8Az1UA+O5LpIa+soacD9XDqTfVisc+LUp+oZv1eFHy+sRx4VUyyEWPs0siEZBdfahYaMok6lNb6bWKx06lZ2L7/bN34ROHNv4t42kXWX8H5OdbkW3ipIwO9ZL7yNcQfcJ8N68XutJWS/s9RwRNFP9g9fwwsV5aBiGUDHu8wAVpCMvfVJhpgfci5p5fFMEGYsVb0W/PAD6Xt4FWYbwE9AB5dXR9Q6tRH9Y4SnJbZ1AY4cc0hss21SnOvwoTLIUwabY7iQAHodqsQLDNvz49hkSLd9Y55umFp/5gXSbJBue92Q2hwULwaayjizn0SYT2Mn2e0gEEsJVWq9/S129LA+MmIE11EQ2obx1EmX4aznvlfMGzyidwmniYY3wRKptulB6y66OSuD4Wq15vTdv5gCmRxQihV9mcTbYVMA+03WEaFnw3/W+Rd4h9Pj5l3ctpjEs3WeYJFIW2tU606iJYvQRuEFloWyZo6CX5vZpxD81O9ao74qgYk2PMRNJ9zH1CmIWE2EhVZhN1oISSsu9Caj0XsAJ78owrEvqLEsWP9gnslIK3KpUsOhe/PM958fngqHnjA0ovM04FRjsL0L3azyvz+IaKof8UyE28j2dMg6gl8YR0=
sudo: false
cache:
  directories:
  - node_modules
  - ".downstream_cache"
