language: node_js
node_js: 8.9.1
before_install: 
- sh -e /etc/init.d/xvfb start
- yarn global add greenkeeper-lockfile@1 yalc
install: yarn --check-files
before_script: greenkeeper-lockfile-update && greenkeeper-lockfile-upload
script:
- if [ "x${DOWNSTREAM_PKGS}${DOWNSTREAM}x" != "xx" ] ; then npm run test:downstream ; else tsc && npm run build ; fi
env:
  global:
  - secure: VlOK/tdM1leqhqigtn/zV2z1s63jaivib5JBTzO5XA3m1lquGsup/exTMoFG+rzylgxD7ccldCSskyk3KYvIvsBngNfDtsf+dnl240+t8AL077ytP2kQ2Ge09JW+Y3B0odI1kgUvTIgLpB2wHB4yCUMvQ0FKPED1qu0EJK5rPltQygK3v7njm8t9M3ki3SjwnfWHzFKu9XZYEokRx7vqcoWGj4pDA9chlXT6s+9xkwQXrp7WP0ZVfi/EtYpt5Ic5sQ6kdivuqvNt7SSDtF6GonbFDDRQ0BHSjIR33tmt0E7bfnVurgRc5KpldoNlYBAJX7gg2EY/aD5X2Rpgc300rG3bO+LO4ghjZhoDcouBK+2zpG74KxKS5cWck4g7qJfqkKAOwpJHXm9sncZSuhYyM4h3dOLYEY1+wUP34VpU2wznyDk99taDYFmbO/QkXvPaN6khyz5wjQsNw72CyIZrWCm5JRyz6fc3n/sLkeyrYc25PVXIL7zSKh3iguLLzuZPWM14cb4GHPAVsFxupWtNaEYS+j99Emg33Wh52T04JQNCiBBaPnYZpRZgdj43gub5KJEve4KBu9vyHn59uN9QGZ61LiaFMsZhHzczW7RcwOnLsm+Ro/UASeCzUu0+bqJ9cLeO6Jk5ff6PmEp0YZZXWkp2EC1oegdl5r4hbSVq/vc=
  matrix:
  - DOWNSTREAM=
  - DOWNSTREAM=true
notifications:
  slack:
    on_success: never
    rooms:
      secure: PTyjJJp3o0kFU2zzjY6rrxsm+9hSz1ffoxhIDgeq6nQwkNJOCWncHVzg7LiHkBpHuWcRQOrLjZd3lHl7g55Bd9529LS9bn7vDEt72eBbbNl4L821SEkkYt+cg88TBTBvQMYgxQrEMSdk6jLGN1ZVhxMerDe9FpASZZL6Of/R9QZuu3nvFB9WT1EwJYhs1365ud4b5TEIDzqS1gephNVsTuQ3BcndYaHj8+4Plobf6M3ZssyQoiTeLCgpZIlk2C5+uJYq6vqABtuFvctaDFN8jOn8zrHN+zOAyw0JRxZn+MaoRXjhLu7A3yXKfzw8nNC4y6JWyPp6SuCRZQi4lGYuu4ZXUTujcWp29g3hCWvPSjZG/0SrMW1PYAxho1N9Bj43aR+xKEA6XiFRzYY5TS4dH6AWrLhfSCMaYeoPh/nD5UdvWcDNDAaFsnXooPdZqg/0U3gkayJsJZrMFVfqH5VpwyYxwWnWhZOrHRXJ8xb9WhTq+EW3kH4tRcFf08Pg7jlL56BuV9QgH7FxApCQic4/0FyV8xWR1hyw1j6zOWNO8q+OrGJHgZ6ixcJKuoG30D+ukLuAFo/V8sg7FTQVrpYkmn8gygmV5AcSexR2l7+73OFvGFUtZYjU+Y7cWU3u8M1iKFbNnMK36FSBdOKxuogkUkQNl9h+xDX+i+y6/EfYvTs=
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
  - ".downstream_cache"
