language: node_js
node_js: 8.9.1
before_install: 
- sh -e /etc/init.d/xvfb start
- yarn global add greenkeeper-lockfile@1 yalc
install: yarn --check-files
before_script: greenkeeper-lockfile-update && greenkeeper-lockfile-upload
script:
- if [ "x${CORE_BRANCH}x" != "xx" ] ; then ./node_modules/.bin/publish_yalc_package
  .downstream_cache/core https://github.com/ui-router/core.git && yalc add @uirouter/core
  ; fi
- yarn test
env:
  global:
    secure: xvwhUuPr1kVLdrUbxP1zSBNlRa283C1L1o97mtjrpRsoss13R8t5L80wIYzKtJ9gqXO+Q49Dnk1jcO/GFcsiANBSR0/z59TaU2WjfcESSFCwiPvSfggRGVetKGIlfUZFtkULz5sWoRDgSlAeY5SW9jEfCEXhcLR8UtS7tfB3dTC7TqSeEPV+hypFEfavjz8a8SOSLqfYvmolsTFTzKtFSmK9WPjGJCRTx1n5OpPlx5I5UCd3FqzgDjDBIKtg1Cx7vZB7tg0X9aN+n/ZJUHl1kmbyzwlhsRQP5KNPhH/puLS5HmjLt807A0c8VhdaKrUwEJ0gr2W8snJU8ICd8t6kcsJcZtOcc/+DHe4PTD/ksbOnuMv0YJoqDSklRHdxFtwvksuINK0tJEyG7rcMY5kebb08gdco6LGlac+NzHim6qIqhHe2PxYmDwFC8fKP0QtPVLPOIM0M77dE6/Zu8pr+hmvhj433VWwBwaYxKgr8vtohoBiOiVsok16vYXtow/JleDDjqGe9SYIXhTjTprDP9Enp8nhwbcmgLrexNPc1WtCm64bgX03M3HxRr5VqgO8daHiasMrL5vBiFoyx+AZz9KRjFh9VQsBH6k+23WP2JCd9JAxzHzlz37Lgdd8xdPT8FKkk3uSqIUC80Wdb/596Qu44KA2J5mNTqXFIYwbtMz4=
  matrix:
  - CORE_BRANCH=
  - CORE_BRANCH=master
matrix:
  fast_finish: true
  allow_failures:
  - env: CORE_BRANCH=
notifications:
  slack:
    on_success: never
    rooms:
      secure: mthnTDooLMpZxdrwiVOzTwAclJXweZHYmIywUYmGVKV5jztElMZnSXvO+iN4FIu6weQSZ4iXI9S3N3CyX5L2EU7Yykyiixxe/0fxNM/W+X3nFKrWq4a1YrB6KHQHE1vFUx/RUTad6zH8bl1Aw3QLlxMXYCZ/sOlqk78CCXdX+6yr7yZ6UqiCWA6h0F24ZT6W4tProCoc4UuyD+NpRJHEsnOahTz7uEiPybzSSyjNCpo6MlXNXa2b1szTx+4s+1oKRhyVHYIvNY0P6QS15+i/ZXaRp+fFEz0jZNadUyKM3mihVYiiWv4ewSJRmhEyMyiD+fQYm1+ttinrBRuIf60NMaKDeaxer41pC2bOhdNkhrrugVXjjL5hv2u1JyzZP7VAtau77paCBDSXwXFUUoboV87C97Rp92/VkcM7jV0d7PtrltmWYPGiPTIReOnrwlsuvbJkDCj05QkF2sf3lkgShBiMpE/XaH/63YUvB8NuQyR5awPlR6XamnAW52uH9iVKx5Lg6Np5hCu2WxMME/qf5K2IfCjaHcLU91lMT/8eo+o6bYgrJs3BXQN7YFkmmZeYmbVXO1o83L0Xlcgf2WWy3nzIRI/v1xyIrGoIFBs/cIWAKB/4Am5hRYzUel9vgInTq//Se0mKMQgbNLkGaFHw4mI220Qz8O0fhs5bUdDfQRs=
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
  - ".downstream_cache"
