language: node_js
node_js: 8.9.1

before_install: yarn global add greenkeeper-lockfile@1 yalc
install: yarn --check-files

before_script: greenkeeper-lockfile-update && greenkeeper-lockfile-upload
script:
- if [ "x${CORE_BRANCH}x" != "xx" ] ; then ./node_modules/.bin/publish_yalc_package
  .downstream_cache/core https://github.com/ui-router/core.git && yalc add @uirouter/core
  ; fi
- yarn test

env:
  global:
    secure: xvwhUuPr1kVLdrUbxP1zSBNlRa283C1L1o97mtjrpRsoss13R8t5L80wIYzKtJ9gqXO+Q49Dnk1jcO/GFcsiANBSR0/z59TaU2WjfcESSFCwiPvSfggRGVetKGIlfUZFtkULz5sWoRDgSlAeY5SW9jEfCEXhcLR8UtS7tfB3dTC7TqSeEPV+hypFEfavjz8a8SOSLqfYvmolsTFTzKtFSmK9WPjGJCRTx1n5OpPlx5I5UCd3FqzgDjDBIKtg1Cx7vZB7tg0X9aN+n/ZJUHl1kmbyzwlhsRQP5KNPhH/puLS5HmjLt807A0c8VhdaKrUwEJ0gr2W8snJU8ICd8t6kcsJcZtOcc/+DHe4PTD/ksbOnuMv0YJoqDSklRHdxFtwvksuINK0tJEyG7rcMY5kebb08gdco6LGlac+NzHim6qIqhHe2PxYmDwFC8fKP0QtPVLPOIM0M77dE6/Zu8pr+hmvhj433VWwBwaYxKgr8vtohoBiOiVsok16vYXtow/JleDDjqGe9SYIXhTjTprDP9Enp8nhwbcmgLrexNPc1WtCm64bgX03M3HxRr5VqgO8daHiasMrL5vBiFoyx+AZz9KRjFh9VQsBH6k+23WP2JCd9JAxzHzlz37Lgdd8xdPT8FKkk3uSqIUC80Wdb/596Qu44KA2J5mNTqXFIYwbtMz4=
  matrix:
  - CORE_BRANCH=
  - CORE_BRANCH=master

matrix:
  fast_finish: true
  allow_failures:
  - env: CORE_BRANCH=

notifications:
  slack:
    secure: y+R7rogX4lNpkDG4u+HEvWcSxmZFXzjTH4dTofLw6/lWovDMmjjFZPVpOf65ms4+ZZrwP6Myg/qwmSig9zqOCYAQIw1c7mIqw96txxzaJKVYUU8oJ5RXQSYMput5gK61wek9gGvw0JAsEzHuT7Y9edYmdh4LbDTSDLNqR+OWHmGVlap5Ma57TlsBghbO/WpT5JTziraInf4tgC7IwW8KvT/3rkblUPZhZ5NOY4+Uv9tTnxjvT0lR28ZKV4B0x9GZ2iOiYQZGMoj/9oIFJoGkVreWG/dyiILkB6HQC9tq+mmUNWa/68AmLZd6lTGM04BbQU4JKxm9V+V1ldTpZuzIyVCfgekXbzHMNLTLTV4S6K7YcTvJLJpccx8IG8toPIG9/OpAV4ISlnh1yxZ1iEX2Jct+8FLjdj+H3fTG6KZyzF8YwC91et5wBpX+BiC2kfZYFJ4FVoq93/Xf4vdLbQIHcjfNkizyMmjz97fux1LoBEpWjx/NRCUAjydPv8XhTi2ql7a09vn+R1TbT7qLiPtBHmaAwomKFiR2odAV5jcmmRpOx1FpKc1wuBSPPydDegjsqe9BjJr2Yef1JSmFbJHNC4VbQNwBUULU57McNH0Pbvi4KbU1dWu93alJRD4GaUyZZMwOEvDatDiCUL5ib4/K3CeyBm6A6Wk+MVuxT25IFgA=

sudo: false

cache:
  yarn: true
  directories:
  - node_modules
  - ".downstream_cache"
